### ISSUE TITLE
Mix up with top/left and bottom/right

### ISSUE THREAD

**Issue by GPSMapper** [taneljairus/random-mapillary-stuff#2]
https://github.com/taneljairus/random-mapillary-stuff/blob/f0063aee08c364dae7c39d1e691a20be381e63d4/ts_processor.py#L367

correct line:
`image = image[args.crop_top : width - args.crop_bottom, args.crop_left : height - args.crop_right]`

**Comment by taneljairus** [comment]
Hopefully fixed.
